baseURL = "https://shamis-08.github.io/hugo-portfolio/"
title = "Portfolio"
theme = "PaperMod"
[pagination]
  pagerSize = 5
enableRobotsTXT = true

[markup.highlight]
style = "monokai"

[params]
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  comments = false

[params.profileMode]
  enabled = true
  title   = "Alena Shamis"
  subtitle = "Student of group P3468"
  imageUrl = "images/avatar.png"
  imageTitle = "Me"
  imageWidth = 160
  imageHeight = 160
