baseURL = "https://shamis-08.github.io/hugo-portfolio/"
title = "Portfolio"
theme = "PaperMod"
[pagination]
  pagerSize = 5
enableRobotsTXT = true

[markup.highlight]
style = "monokai"

[params]
  homeInfoParams = { Title = "Alena Shamis", Content = "Student of group P3468" }
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  comments = false
